--liquibase formatted sql

--changeset alex.kiselev.dev@gmail.com: engine_init runInTransaction:true failOnError:true dbms:postgresql
create table if not exists car(
 "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    "power" integer not null,
    "weight_engine" integer not null,
    "price_engine" integer not null,

    "model" varchar not null,
    "material" varchar not null,
    "weight_body" integer not null,
    "price_body" integer not null,

    "weight_sheathing" integer not null,
    "price_sheathing" integer not null
);


--rollback DROP TABLE car;